project_id = "nzngwbknezmfthbyfjmx"

[functions.register]
verify_jwt = false

[functions.sync-user]
verify_jwt = false

[functions.ai-edit]
verify_jwt = false

[functions.test-ai-provider]
verify_jwt = false
