
export const PREMIUM_FONTS = [
  { id: 'inter', name: 'Inter', family: 'var(--font-inter), Inter, sans-serif', weight: 500 },
  { id: 'space-grotesk', name: 'Space', family: 'var(--font-space-grotesk), sans-serif', weight: 600 },
  { id: 'syne', name: 'Syne', family: 'var(--font-syne), sans-serif', weight: 700 },
  { id: 'outfit', name: 'Outfit', family: 'var(--font-outfit), sans-serif', weight: 600 },
  { id: 'dm-sans', name: 'DM Sans', family: 'var(--font-dm-sans), sans-serif', weight: 500 },
  { id: 'raleway', name: 'Raleway', family: 'var(--font-raleway), sans-serif', weight: 600 },
  { id: 'bebas-neue', name: 'Bebas Neue', family: 'var(--font-bebas-neue), sans-serif', weight: 400 },
  { id: 'playfair', name: 'Playfair', family: 'var(--font-playfair), serif', weight: 400 },
  { id: 'caveat', name: 'Caveat', family: 'var(--font-caveat), cursive', weight: 600 },
  { id: 'montserrat', name: 'Montserrat', family: 'var(--font-montserrat), Montserrat, sans-serif', weight: 700 },
  { id: 'plus-jakarta', name: 'Jakarta', family: 'var(--font-plus-jakarta), "Plus Jakarta Sans", sans-serif', weight: 700 },
  { id: 'manrope', name: 'Manrope', family: 'var(--font-manrope), Manrope, sans-serif', weight: 700 },
  { id: 'urbanist', name: 'Urbanist', family: 'var(--font-urbanist), Urbanist, sans-serif', weight: 400 },
];

export const OVERLAY_STYLES: Record<string, string> = {
  none: 'none',
  gradient: 'linear-gradient(to bottom, transparent 0%, rgba(0,0,0,0.6) 100%)',
  'gradient-strong': 'linear-gradient(to bottom, transparent 0%, rgba(0,0,0,0.9) 100%)',
  vignette: 'radial-gradient(circle, transparent 20%, rgba(0,0,0,0.4) 100%)',
  'vignette-strong': 'radial-gradient(circle, transparent 0%, rgba(0,0,0,0.7) 100%)',
  dark: 'rgba(0,0,0,0.4)',
  'dark-strong': 'rgba(0,0,0,0.7)',
  bottom: 'linear-gradient(to top, rgba(0,0,0,0.8) 0%, transparent 50%)',
  'bottom-strong': 'linear-gradient(to top, rgba(0,0,0,0.95) 0%, transparent 65%)',
  'bottom-intense': 'linear-gradient(to top, rgba(0,0,0,1) 0%, rgba(0,0,0,0.6) 40%, transparent 70%)',
  top: 'linear-gradient(to bottom, rgba(0,0,0,0.8) 0%, transparent 50%)',
  'top-strong': 'linear-gradient(to bottom, rgba(0,0,0,0.95) 0%, transparent 65%)',
  'top-intense': 'linear-gradient(to bottom, rgba(0,0,0,1) 0%, rgba(0,0,0,0.6) 40%, transparent 70%)',
  frame: 'linear-gradient(to bottom, rgba(0,0,0,0.5) 0%, transparent 20%, transparent 80%, rgba(0,0,0,0.5) 100%)',
  'frame-strong': 'linear-gradient(to bottom, rgba(0,0,0,0.8) 0%, transparent 25%, transparent 75%, rgba(0,0,0,0.8) 100%)',
  left: 'linear-gradient(to right, rgba(0,0,0,0.85) 0%, transparent 60%)',
  right: 'linear-gradient(to left, rgba(0,0,0,0.85) 0%, transparent 60%)',
  'diag-bl': 'linear-gradient(to top right, rgba(0,0,0,0.9) 0%, transparent 60%)',
  'diag-br': 'linear-gradient(to top left, rgba(0,0,0,0.9) 0%, transparent 60%)',
  'diag-tl': 'linear-gradient(to bottom right, rgba(0,0,0,0.9) 0%, transparent 60%)',
  'diag-tr': 'linear-gradient(to bottom left, rgba(0,0,0,0.9) 0%, transparent 60%)',
};

export const BACKGROUND_PATTERNS: Record<string, string> = {
  none: '',
  grid: 'radial-gradient(circle, currentColor 1px, transparent 1px)',
  dots: 'radial-gradient(currentColor 1.5px, transparent 1.5px)',
  lines: 'repeating-linear-gradient(0deg, currentColor, currentColor 1px, transparent 1px, transparent 40px)',
  diagonal: 'repeating-linear-gradient(45deg, currentColor, currentColor 1px, transparent 1px, transparent 20px)',
  crosshatch: 'repeating-linear-gradient(45deg, currentColor, currentColor 1px, transparent 1px, transparent 20px), repeating-linear-gradient(-45deg, currentColor, currentColor 1px, transparent 1px, transparent 20px)',
};

export const OVERLAY_OPTIONS = [
  { value: 'none',          label: 'Nenhum' },
  { value: 'gradient',      label: 'Gradiente' },
  { value: 'gradient-strong', label: 'Gradiente Forte' },
  { value: 'vignette',      label: 'Vinheta' },
  { value: 'vignette-strong', label: 'Vinheta Forte' },
  { value: 'dark',          label: 'Escurecido' },
  { value: 'dark-strong',   label: 'Escurecido Forte' },
  { value: 'bottom',        label: 'Baixo' },
  { value: 'bottom-strong', label: 'Baixo Forte' },
  { value: 'bottom-intense',label: 'Baixo Intenso' },
  { value: 'top',           label: 'Topo' },
  { value: 'top-strong',    label: 'Topo Forte' },
  { value: 'top-intense',   label: 'Topo Intenso' },
  { value: 'frame',         label: 'Frame' },
  { value: 'frame-strong',  label: 'Frame Forte' },
  { value: 'left',          label: 'Esquerda' },
  { value: 'right',         label: 'Direita' },
  { value: 'diag-bl',       label: 'Diagonal ↗' },
  { value: 'diag-br',       label: 'Diagonal ↖' },
  { value: 'diag-tl',       label: 'Diagonal ↘' },
  { value: 'diag-tr',       label: 'Diagonal ↙' },
];
